language: node_js
branches:
  only:
    - master
node_js:
  - 0.10
before_script:
  - 'npm install -g grunt-cli coveralls'
script:
  - 'grunt test:parts && cat reports/coverage/lcov.info | coveralls'
