language: node_js
branches:
  only:
    - master
node_js:
  - 0.10
before_script:
  - 'npm install -g grunt-cli coveralls'
script:
  - 'grunt spec && cat generated/reports/spec/lcov.info | coveralls'
